<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img_ad</name>
   <tag></tag>
   <elementGuidId>4bd9fa0a-6128-41c0-a0c5-2c308071c22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img_ad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='aw0']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>224b86e8-fdd3-41bd-b272-43445e87b129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://tpc.googlesyndication.com/simgad/2577437580630296244?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&amp;rs=AOga4qnNKvPGL5r03CcwYzsDXDvvWTMZig</value>
      <webElementGuid>75d52658-cb5d-4847-ae33-6003b041b4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae979e59-dec6-4f44-ad10-2fc51b61b974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>414</value>
      <webElementGuid>ecd54d46-1571-493e-ab96-f47f5b8afc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_ad</value>
      <webElementGuid>1e22562f-723c-448d-9571-966f6fac5e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aw0&quot;)/img[@class=&quot;img_ad&quot;]</value>
      <webElementGuid>2fc8d677-1f28-431d-976e-9a2efd554340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SESI 3/BLOG/001-ads-click/iframe_Donate_aswift_1</value>
      <webElementGuid>45980f1b-668d-43ea-9e69-880a60e0eccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='aw0']/img</value>
      <webElementGuid>fa7e59fa-15ad-4c7e-a2bb-e50a2f481625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://tpc.googlesyndication.com/simgad/2577437580630296244?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&amp;rs=AOga4qnNKvPGL5r03CcwYzsDXDvvWTMZig')]</value>
      <webElementGuid>ffae22bb-d436-453e-871e-940b0089b0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cf8c3d27-8e2f-40bd-99df-c8a75b18dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://tpc.googlesyndication.com/simgad/2577437580630296244?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&amp;rs=AOga4qnNKvPGL5r03CcwYzsDXDvvWTMZig']</value>
      <webElementGuid>b8ad3c52-b3af-4d57-9448-6cfe4f0c4fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
